# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  tagrelease:
    working_directory: ~/repo
    docker:
    - image: circleci/python:2.7

    steps:
    - checkout
    - run:
        name: Tag release
        command: |
          sudo pip install -r bumpversion
          LATEST_VERSION=`git describe --tags | cut -f1 -d- | sed 's/^v//'`
          bumpversion --current-version ${LATEST_VERSION} --tag minor
          git push --tags
workflows:
  version: 2
  build-and-deploy:
    jobs:
    - tagrelease:
        filters:
          branches:
            only: master
