# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

bumpversion: &bumpversion
  name: bump package version
  command: |
    PATH=$PATH:~/.local/bin
    pip install --user bump2version tox
    set +o pipefail
    LATEST_VERSION=$(curl --silent "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/latest" | jq -r '.tag_name // empty')
    set -o pipefail
    [  -z "$LATEST_VERSION" ] && LATEST_VERSION="0.0.0"
    sed -i -e "s/version=\"0.0.0\"/version=\"$LATEST_VERSION\"/" setup.py
    bump2version minor --current-version $LATEST_VERSION

configureAWS: &configureAWS
  name: Configure AWS
  command: |
    mkdir ~/.aws
    cat >> ~/.aws/config << EOF
    [default]
    region = eu-west-2
    EOF

jobs:
  test_2.7:
    working_directory: ~/repo
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: *bumpversion
      - run: *configureAWS
      - run:
          name: Test Python-2.7
          command: AWS_DEFAULT_REGION=eu-west-2 ~/.local/bin/tox -e py27

  test_3.7:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: *bumpversion
      - run: *configureAWS
      - run:
          name: Test Python-3.7
          command: AWS_DEFAULT_REGION=eu-west-2 ~/.local/bin/tox -e py37

  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: *bumpversion
      - run:
          name: Create dist package
          command: python setup.py sdist --dist-dir artifacts

      - persist_to_workspace:
          root: artifacts
          paths:
            - acm_pca_cert_generator-*.tar.gz

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run: *bumpversion
      - run:
          name: Create GitHub release
          command: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test_2.7
      - test_3.7
      - build:
          requires:
            - test_2.7
            - test_3.7
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              only: master
