# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
    - image: circleci/python:2.7

    steps:
    - checkout
    - run:
        name: create dist package
        command: |
          PATH=$PATH:~/.local/bin
          pip install --user bump2version tox
          set +o pipefail
          LATEST_VERSION=$(curl --silent "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/latest" | jq -r '.tag_name // empty')
          set -o pipefail
          [  -z "$LATEST_VERSION" ] && LATEST_VERSION="0.0.0"
          echo "LATEST_VERSION=$LATEST_VERSION"
          sed -i -e "s/version=\"0.0.0\"/version=\"$LATEST_VERSION\"/" setup.py
          cat setup.py
          bump2version minor --current-version $LATEST_VERSION
          tox
          python setup.py sdist --dist-dir artifacts

    - persist_to_workspace:
        root: artifacts
        paths:
        - acm_pca_cert_generator-*.tar.gz
  publish-github-release:
    docker:
    - image: cibuilds/github:0.10
    steps:
    - attach_workspace:
        at: ./artifacts
    - run:
        name: "Publish Release on GitHub"
        command: |
          PATH=$PATH:~/.local/bin
          pip install --user bump2version
          set -u
          set +o pipefail
          LATEST_VERSION=$(curl --silent "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/latest" | jq -r '.tag_name' // empty)
          set -o pipefail
          [  -z "$LATEST_VERSION" ] && LATEST_VERSION="0.0.0"
          sed -i -e "s/version=\"0.0.0\"/version=\"$LATEST_VERSION\"/" setup.py
          VERSION=$(bump2version minor --current-version $LATEST_VERSION --list | grep new_version | cut -f2 -d=)
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build
    - publish-github-release:
        requires:
        - build
        filters:
          branches:
            only: master
