# To use the same mirroring approach in a new repo, copy 'ci' directory and aviator.yml,
# then replace references to Github repo in:
# - resources.yml
# - aviator.yml
# - jobs/mirror-job.yml

jobs:
  - name: mirror-acm-pca-cert-generator
    plan:
      - get: aws-management-infrastructure
      - get: acm-pca-cert-generator
        trigger: true
        params:
          globs:
            - "*.tar.gz"
      - .: (( inject meta.plan.terraform-output ))
      - task: mirror-acm-pca-cert-generator
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((dataworks.docker_awscli_repository))
              version: ((dataworks.docker_awscli_version))
              tag: ((dataworks.docker_awscli_version))
          inputs:
            - name: bucket_name
            - name: acm-pca-cert-generator
          params:
            ARTEFACT_DIR: "acm-pca-cert-generator"
            AWS_ROLE_ARN: arn:aws:iam::((dataworks.aws_management_acc)):role/ci
            AWS_DEFAULT_REGION: ((dataworks.aws_region))
          run:
            path: sh
            args:
              - -exc
              - |
                source /assume-role
                set +x
                export BUCKET=`cat bucket_name/bucket_name`
                aws s3 cp ${ARTEFACT_DIR}/*.tar.gz s3://${BUCKET}/${ARTEFACT_DIR}/
