jobs:
  - name: update-pipeline
    plan:
      - get: acm-pca-cert-generator
        resource: acm-pca-cert-generator-update-pipeline
        trigger: true
      - task: aviator
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((dataworks.docker_aviator_repository))
              version: ((dataworks.docker_aviator_version))
          run:
            path: sh
            args:
              - -exc
              - |
                sed -i 's/fly/nofly/' aviator.yml
                /usr/bin/aviator -f aviator.yml
                mv aviator_pipeline.yml ../pipeline
            dir: acm-pca-cert-generator
          inputs:
            - name: acm-pca-cert-generator
          outputs:
            - name: pipeline
      - set_pipeline: asset-mgmt-acm-pca-cert-generator
        file: pipeline/aviator_pipeline.yml
